default:
	make -C ..

build:
	make -C .. build

index:
	make -C .. index

clean:
	make -C .. clean
	rm -f ${NAME}.aux
	rm -f ${NAME}.log
	rm -f ${NAME}.toc
	rm -f ${NAME}.out
	rm -f ${NAME}.idx
	rm -f ${NAME}.ilg
	rm -f ${NAME}.ind
	rm -f -v *.aux
